name: Build & Publish Carplay Module Image

on:
  # push:
  #   branches: [custom_image]
  #   paths:
  #     - 'docker/**'
  #     - '.github/workflows/build-carplay.yml'
  workflow_dispatch: {}

jobs:
  build:
    name: Build & Push Multi-Arch Image
    runs-on: [self-hosted, Linux, X64, abby-docker-build]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (amd64 + arm64)
        uses: docker/build-push-action@v6
        with:
          context: .                         
          file: docker/common/Dockerfile     
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/car-pi/carplay-module:latest
            ghcr.io/car-pi/carplay-module:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/car-pi/carplay-module:cache
          cache-to:   type=registry,ref=ghcr.io/car-pi/carplay-module:cache,mode=max
